"""add playback confirmation fields

Revision ID: 4215b315a818
Revises: b6c524152658
Create Date: 2026-07-19 00:26:02.003396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4215b315a818'
down_revision: Union[str, Sequence[str], None] = 'b6c524152658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_events', sa.Column('duration_ms', sa.BigInteger(), nullable=True))
    op.add_column('play_events', sa.Column('played_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_events', 'played_reason')
    op.drop_column('play_events', 'duration_ms')
    # ### end Alembic commands ###
