"""add play_events listening history

Revision ID: 71a4a909b424
Revises: e4a3d0a9529d
Create Date: 2026-07-18 23:21:12.992240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a4a909b424'
down_revision: Union[str, Sequence[str], None] = 'e4a3d0a9529d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('uploader', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('source_query', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('played_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('played_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_play_events_guild_time', 'play_events', ['guild_id', 'played_at'], unique=False)
    op.create_index('ix_play_events_guild_track_time', 'play_events', ['guild_id', 'track_id', 'played_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_play_events_guild_track_time', table_name='play_events')
    op.drop_index('ix_play_events_guild_time', table_name='play_events')
    op.drop_table('play_events')
    # ### end Alembic commands ###
